# Separação de datasets
#### O objetivo desse notebook é separar o dataset principal em datasets de treino e teste

## Import de frameworks

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import f1_score

## Separação

In [2]:
data_raw = pd.read_csv('datasets/spi_indicators.csv')
data_raw.head(2)

,iso3c,country,region,income,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
0,DNK,Denmark,Europe & Central Asia,High income,2023,5946952,95.255833,100.0,98.466667,90.71250,87.100,100.0
1,FIN,Finland,Europe & Central Asia,High income,2023,5584264,95.115417,100.0,96.433333,90.96875,88.175,100.0

In [3]:
data_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   iso3c                      4340 non-null   str
 1   country                    4340 non-null   str
 2   region                     4340 non-null   str
 3   income                     4340 non-null   str
 4   year                       4340 non-null   int64
 5   population                 4340 non-null   int64
 6   overall_score              1425 non-null   float64
 7   data_use_score             4340 non-null   float64
 8   data_services_score        1436 non-null   float64
 9   data_products_score        4085 non-null   float64
 10  data_sources_score         1560 non-null   float64
 11  data_infrastructure_score  1519 non-null   float64
dtypes: float64(6), int64(2), str(4)
memory usage: 407.0 KB

In [4]:
data_raw.describe(include='all')

,iso3c,country,region,income,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
count,4340,4340,4340,4340,4340.000000,4.340000e+03,1425.000000,4340.000000,1436.000000,4085.000000,1560.000000,1519.000000
unique,217,217,7,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,DNK,Denmark,Europe & Central Asia,High income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,20,20,1160,1700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,2013.500000,3.338109e+07,64.947420,50.745714,64.781546,55.212702,51.891090,54.944042
std,NaN,NaN,NaN,NaN,5.766946,1.321476e+08,17.511148,29.468643,23.474755,18.684428,20.057036,28.223303
min,NaN,NaN,NaN,NaN,2004.000000,9.791000e+03,11.769583,0.000000,0.333333,4.893750,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,2008.750000,7.441640e+05,52.835833,30.000000,56.183333,45.506250,36.881250,30.000000
50%,NaN,NaN,NaN,NaN,2013.500000,5.940858e+06,64.282500,40.000000,64.000000,58.025000,52.816667,50.000000
75%,NaN,NaN,NaN,NaN,2018.250000,2.167538e+07,80.197083,80.000000,86.466667,68.431250,68.629167,80.000000
max,NaN,NaN,NaN,NaN,2023.000000,1.428628e+09,95.255833,100.000000,100.000000,94.312500,94.175000,100.000000

In [5]:
data_raw.income.value_counts()

income
High income            1700
Upper middle income    1080
Lower middle income    1020
Low income              520
Not classified           20
Name: count, dtype: int64

Excluirei as colunas iso3c e country por serem muito específicas, podendo ser um ponto fácil pro modelo adivinhar qual é o income correto. Também excluirei o income classificado como "Not classified".

In [6]:
df_filt = data_raw.drop(columns=['iso3c', 'country']).copy()
df_filt = df_filt[df_filt['income'] != 'Not classified']
df_filt.head(2)

,region,income,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
0,Europe & Central Asia,High income,2023,5946952,95.255833,100.0,98.466667,90.71250,87.100,100.0
1,Europe & Central Asia,High income,2023,5584264,95.115417,100.0,96.433333,90.96875,88.175,100.0

In [7]:
df_filt.describe(include='all')

,region,income,year,population,overall_score,data_use_score,data_services_score,data_products_score,data_sources_score,data_infrastructure_score
count,4320,4320,4320.000000,4.320000e+03,1417.000000,4320.000000,1428.000000,4066.000000,1551.000000,1511.000000
unique,7,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Europe & Central Asia,High income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1160,1700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2013.500000,3.340240e+07,65.052884,50.740741,64.850187,55.198148,51.982855,55.102581
std,NaN,NaN,5.766949,1.324528e+08,17.501637,29.522559,23.503276,18.724464,20.076224,28.213461
min,NaN,NaN,2004.000000,9.791000e+03,11.769583,0.000000,0.333333,4.893750,0.000000,0.000000
25%,NaN,NaN,2008.750000,7.298842e+05,53.153333,30.000000,56.233333,45.462500,37.200000,30.000000
50%,NaN,NaN,2013.500000,5.854352e+06,64.706250,40.000000,64.033333,58.006250,53.241667,50.000000
75%,NaN,NaN,2018.250000,2.124189e+07,80.322500,80.000000,86.466667,68.448438,68.725000,80.000000
max,NaN,NaN,2023.000000,1.428628e+09,95.255833,100.000000,100.000000,94.312500,94.175000,100.000000

In [8]:
df_filt.year.unique()

array([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013,
       2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004])

In [9]:
len(df_filt.year.unique())

20

A divisão mais correta, olhando para os dados seria separar entre 2004 e 2019 para termos 80% dos dados e 20% para teste. É importante ressaltar que provavelmente a pandemia pode afetar o modelo, todavia, como o propósito é estudar o optuna, isso será considerado para a modelagem.

In [ ]:
dataset_train = df_filt[df_filt.year < 2020].copy()
dataset_test = df_filt[df_filt.year >= 2020].copy()

In [ ]:
dataset_train.to_csv('datasets/dataset_train.csv', index=False)
dataset_test.to_csv('datasets/dataset_test.csv', index=False)