In [23]:
# Imports
import importlib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import ml_pokedex as mlpo
importlib.reload(mlpo)

In [12]:
# Carregar dataset Iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [13]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [25]:
# Exemplo: aplicar na variável "sepal length (cm)"
df_results, best_transforms = mlpo.apply_scaling(df, df.columns)
df_results

c:\Users\Dell\Documents\Códigos\PoupaTempos\ML-Pokedex\.venv3\Lib\site-packages\sklearn\preprocessing\_data.py:2885: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  warnings.warn(
c:\Users\Dell\Documents\Códigos\PoupaTempos\ML-Pokedex\.venv3\Lib\site-packages\sklearn\preprocessing\_data.py:2885: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  warnings.warn(
c:\Users\Dell\Documents\Códigos\PoupaTempos\ML-Pokedex\.venv3\Lib\site-packages\sklearn\preprocessing\_data.py:2885: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  warnings.warn(
c:\Users\Dell\Documents\Códigos\PoupaTempos\ML-Pokedex\.venv3\Lib\site-packages\sklearn\preprocessing\_data.py:2885: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  warnings.warn(

               coluna        transformacao       p_value  is_normal
0   sepal length (cm)             Original  5.682425e-02       True
1   sepal length (cm)       StandardScaler  5.682425e-02       True
2   sepal length (cm)         MinMaxScaler  5.682425e-02       True
3   sepal length (cm)         RobustScaler  5.682425e-02       True
4   sepal length (cm)         MaxAbsScaler  5.682425e-02       True
5   sepal length (cm)  QuantileTransformer  1.818261e-05      False
6   sepal length (cm)     PowerTransformer  1.624851e-02      False
7    sepal width (cm)             Original  2.097338e-01       True
8    sepal width (cm)       StandardScaler  2.097338e-01       True
9    sepal width (cm)         MinMaxScaler  2.097338e-01       True
10   sepal width (cm)         RobustScaler  2.097338e-01       True
11   sepal width (cm)         MaxAbsScaler  2.097338e-01       True
12   sepal width (cm)  QuantileTransformer  1.714154e-05      False
13   sepal width (cm)     PowerTransformer  9.232471e-01       True
14  petal length (cm)             Original  7.264668e-49      False
15  petal length (cm)       StandardScaler  7.264668e-49      False
16  petal length (cm)         MinMaxScaler  7.264668e-49      False
17  petal length (cm)         RobustScaler  7.264668e-49      False
18  petal length (cm)         MaxAbsScaler  7.264668e-49      False
19  petal length (cm)  QuantileTransformer  1.861278e-05      False
20  petal length (cm)     PowerTransformer  7.421675e-44      False
21   petal width (cm)             Original  1.349279e-30      False
22   petal width (cm)       StandardScaler  1.349279e-30      False
23   petal width (cm)         MinMaxScaler  1.349279e-30      False
24   petal width (cm)         RobustScaler  1.349279e-30      False
25   petal width (cm)         MaxAbsScaler  1.349279e-30      False
26   petal width (cm)  QuantileTransformer  6.911604e-08      False
27   petal width (cm)     PowerTransformer  3.068602e-35      False

In [27]:
best_transforms

               coluna        transformacao       p_value  is_normal
13   sepal width (cm)     PowerTransformer  9.232471e-01       True
0   sepal length (cm)             Original  5.682425e-02       True
19  petal length (cm)  QuantileTransformer  1.861278e-05      False
26   petal width (cm)  QuantileTransformer  6.911604e-08      False